"""Operational contract models for Phase 1."""

from .base import (
    StrictModel,
    VersionedContract,
    HumanSuppliedText,
    NonBlankText,
    SessionId,
    ActorUrn,
    RequestId,
    ContractKind,
)
from .data_operations import (
    DATA_OPERATION_ADAPTER,
    CreateDeliveryRequestRequest,
    DataOperationRequest,
    DataOperationResult,
    GetRequestRoutingContextRequest,
    ReadDeliveryRequestRequest,
    SetRequestStatusRequest,
    UpdateDeliveryRequestRequest,
    data_operation_request_schema,
    validate_data_operation_request,
)
from .enums import (
    RequestStatus,
    IntakeField,
    DataOperation,
    ErrorCode,
    ActorRole,
    IdentityAssurance,
    InvocationSource,
    BindingState,
    RoutingStage,
    RouterOutcome,
    RouterTarget,
    RoutingReason,
    IntakeOutcome,
    DataOperationOutcome,
    CallerFlow,
    ErrorCategory,
    ErrorEscalation,
    DependencyKind,
    FailureKind,
    RetryAction,
    POST_INTAKE_STATUSES,
)
from .errors import OperationalError, FieldViolation, ERROR_POLICY
from .envelope import ActorContext, MainFlowInput
from .routing import RoutingLookupRecord, RoutingContext, RouterResult, adapt_routing_lookup

__all__ = [
    # Base
    "StrictModel",
    "VersionedContract",
    "HumanSuppliedText",
    "NonBlankText",
    "SessionId",
    "ActorUrn",
    "RequestId",
    "ContractKind",
    # Data Operations (Task 8)
    "DataOperationRequest",
    "DataOperationResult",
    "GetRequestRoutingContextRequest",
    "CreateDeliveryRequestRequest",
    "ReadDeliveryRequestRequest",
    "UpdateDeliveryRequestRequest",
    "SetRequestStatusRequest",
    "DATA_OPERATION_ADAPTER",
    "validate_data_operation_request",
    "data_operation_request_schema",
    # Enums
    "RequestStatus",
    "IntakeField",
    "DataOperation",
    "ErrorCode",
    "ActorRole",
    "IdentityAssurance",
    "InvocationSource",
    "BindingState",
    "RoutingStage",
    "RouterOutcome",
    "RouterTarget",
    "RoutingReason",
    "IntakeOutcome",
    "DataOperationOutcome",
    "CallerFlow",
    "ErrorCategory",
    "ErrorEscalation",
    "DependencyKind",
    "FailureKind",
    "RetryAction",
    "POST_INTAKE_STATUSES",
    # Errors
    "OperationalError",
    "FieldViolation",
    "ERROR_POLICY",
    # Envelope
    "ActorContext",
    "MainFlowInput",
    # Routing
    "RoutingLookupRecord",
    "RoutingContext",
    "RouterResult",
    "adapt_routing_lookup",
]
