#!/usr/bin/env python3
"""Whole-model Mermaid class diagram generator (built on LinkML ``Generator``).

LinkML's ``gen-mermaid-class-diagram`` only writes one file *per class*. This
emits a single Mermaid ``classDiagram`` for the whole schema, wrapped in a
Markdown fence so it renders inline on GitHub — the diagram stays generated
(regenerates with the model), never hand-authored.

Mapping (mirrors gen-plantuml): ``is_a`` -> inheritance edge; object-valued slot
-> association (composition ``*--`` when the target is a value object with no
identifier, else ``-->``), labelled with the slot name and target cardinality.
Relationships are emitted on the class that *owns* the slot; subclasses inherit
via the inheritance edge.

Usage:  python scripts/gen_mermaid_classdiagram.py model/linkml/hulubul.yaml
   or:  gen-mermaid-classdiagram model/linkml/hulubul.yaml   (once installed)
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar

import click
from linkml.utils.generator import Generator, shared_arguments  # type: ignore[import-untyped]


def _cardinality(required: bool, multivalued: bool) -> str:
    lo = "1" if required else "0"
    hi = "*" if multivalued else "1"
    return hi if lo == hi else f"{lo}..{hi}"


@dataclass
class MermaidClassDiagramGenerator(Generator):  # type: ignore[misc]
    """Emit one Mermaid classDiagram covering every class in the schema."""

    generatorname: ClassVar[str] = "gen-mermaid-classdiagram"
    generatorversion: ClassVar[str] = "1.0.0"
    valid_formats: ClassVar[list[str]] = ["markdown"]
    file_extension: ClassVar[str] = "md"
    uses_schemaloader: ClassVar[bool] = False

    def _collect(self) -> tuple[dict[str, list[str]], list[str], list[str]]:
        """Return per-class attribute lines, inheritance edges and association edges.

        Only *directly declared* slots are shown per class; inherited attributes
        live on the ancestor and are carried by the inheritance edge (clean UML).
        Scalar/enum slots become attributes; object-valued slots become edges.
        """
        sv = self.schemaview
        class_names = set(sv.all_classes())
        attrs: dict[str, list[str]] = {}
        inheritance: list[str] = []
        associations: list[str] = []

        for cn in sorted(class_names):
            cls = sv.get_class(cn)
            if cls.is_a:
                inheritance.append(f"    {cls.is_a} <|-- {cn}")
            lines: list[str] = []
            for slot_name in sv.class_slots(cn, direct=True):
                slot = sv.induced_slot(slot_name, cn)
                if slot.range in class_names:  # object-valued -> association edge
                    target_has_id = sv.get_identifier_slot(slot.range) is not None
                    arrow = "-->" if target_has_id else "*--"  # composition for value objects
                    card = _cardinality(bool(slot.required), bool(slot.multivalued))
                    associations.append(f'    {cn} {arrow} "{card}" {slot.range} : {slot.name}')
                else:  # scalar/enum -> attribute
                    suffix = "[]" if slot.multivalued else ""
                    lines.append(f"        +{slot.range} {slot.name}{suffix}")
            attrs[cn] = lines
        return attrs, inheritance, associations

    def serialize(self, **kwargs: Any) -> str:
        attrs, inheritance, associations = self._collect()
        class_decls: list[str] = []
        for cn in sorted(attrs):
            if attrs[cn]:
                class_decls.append(f"    class {cn} {{")
                class_decls.extend(attrs[cn])
                class_decls.append("    }")
            else:
                class_decls.append(f"    class {cn}")
        body = "\n".join([*class_decls, "", *inheritance, "", *associations])
        return (
            f"# {self.schema.name} — class diagram (whole model)\n\n"
            "<!-- Generated by gen-mermaid-classdiagram. DO NOT EDIT — "
            "regenerate with `make classdiagram`. -->\n\n"
            "```mermaid\nclassDiagram\n" + body + "\n```\n"
        )


@shared_arguments(MermaidClassDiagramGenerator)
@click.command(name="gen-mermaid-classdiagram")
@click.version_option(MermaidClassDiagramGenerator.generatorversion, "-V", "--version")
def cli(yamlfile: str, **kwargs: Any) -> None:
    """Generate a single whole-model Mermaid class diagram from a LinkML schema."""
    gen = MermaidClassDiagramGenerator(yamlfile, **kwargs)
    print(gen.serialize())


if __name__ == "__main__":
    cli()
