#!/usr/bin/env python3
"""Whole-model Mermaid class diagram generator (built on LinkML ``Generator``).

LinkML's ``gen-mermaid-class-diagram`` only writes one file *per class*. This
emits a single Mermaid ``classDiagram`` for the whole schema, wrapped in a
Markdown fence so it renders inline on GitHub — the diagram stays generated
(regenerates with the model), never hand-authored.

Mapping (mirrors gen-plantuml): ``is_a`` -> inheritance edge; object-valued slot
-> association (composition ``*--`` when the target is a value object with no
identifier, else ``-->``), labelled with the slot name and target cardinality.
Relationships are emitted on the class that *owns* the slot; subclasses inherit
via the inheritance edge.

Usage:  python scripts/gen_mermaid_classdiagram.py model/linkml/hulubul.yaml
   or:  gen-mermaid-classdiagram model/linkml/hulubul.yaml   (once installed)
"""
from __future__ import annotations

from dataclasses import dataclass

import click
from linkml.utils.generator import Generator, shared_arguments


def _cardinality(required: bool, multivalued: bool) -> str:
    lo = "1" if required else "0"
    hi = "*" if multivalued else "1"
    return hi if lo == hi else f"{lo}..{hi}"


@dataclass
class MermaidClassDiagramGenerator(Generator):
    """Emit one Mermaid classDiagram covering every class in the schema."""

    generatorname = "gen-mermaid-classdiagram"
    generatorversion = "1.0.0"
    valid_formats = ["markdown"]
    file_extension = "md"
    uses_schemaloader = False

    def _edges(self) -> tuple[list[str], list[str]]:
        sv = self.schemaview
        class_names = set(sv.all_classes())
        inheritance: list[str] = []
        associations: list[str] = []

        for cn in sorted(class_names):
            cls = sv.get_class(cn)
            if cls.is_a:
                inheritance.append(f"    {cls.is_a} <|-- {cn}")
            for slot_name in sv.class_slots(cn, direct=True):
                slot = sv.induced_slot(slot_name, cn)
                if slot.range not in class_names:  # scalar/enum -> a property, not an edge
                    continue
                target_has_id = sv.get_identifier_slot(slot.range) is not None
                arrow = "-->" if target_has_id else "*--"  # composition for value objects
                card = _cardinality(bool(slot.required), bool(slot.multivalued))
                associations.append(f'    {cn} {arrow} "{card}" {slot.range} : {slot.name}')
        return inheritance, associations

    def serialize(self, **kwargs) -> str:
        inheritance, associations = self._edges()
        class_decls = [f"    class {cn}" for cn in sorted(self.schemaview.all_classes())]
        body = "\n".join(class_decls + [""] + inheritance + [""] + associations)
        return (
            f"# {self.schema.name} — class diagram (whole model)\n\n"
            "<!-- Generated by gen-mermaid-classdiagram. DO NOT EDIT — "
            "regenerate with `make classdiagram-full`. -->\n\n"
            "```mermaid\nclassDiagram\n" + body + "\n```\n"
        )


@shared_arguments(MermaidClassDiagramGenerator)
@click.command(name="gen-mermaid-classdiagram")
@click.version_option(MermaidClassDiagramGenerator.generatorversion, "-V", "--version")
def cli(yamlfile, **kwargs):
    """Generate a single whole-model Mermaid class diagram from a LinkML schema."""
    gen = MermaidClassDiagramGenerator(yamlfile, **kwargs)
    print(gen.serialize())


if __name__ == "__main__":
    cli()
