"""
Test that all Docker services and Python dependencies are pinned to approved digest SHAs.

This test enforces reproducible runtime versions — no mutable tags or unhashed dependencies.
"""

import re
from pathlib import Path

import yaml  # type: ignore[import-untyped]

# Approved digest SHAs (verified against public docker.io/PyPI before implementation)
LANGFLOW_IMAGE = "langflowai/langflow:1.10.2@sha256:ae6f9afd03bc032dc2989ece49791fcf83871230aff9d6e485c8e1ebada1e70f"
POSTGRES_IMAGE = (
    "postgres:16-trixie@sha256:33f923b05f64ca54ac4401c01126a6b92afe839a0aa0a52bc5aeb5cc958e5f20"
)
NEO4J_IMAGE = (
    "neo4j:5.26-community@sha256:362542416de6c09a971484d1893878016cc3b5cdec166e54b1c824a220ecd6b9"
)
PYTHON_BASE_IMAGE = (
    "python:3.12-slim@sha256:57cd7c3a7a273101a6485ba99423ee568157882804b1124b4dd04266317710de"
)

# MCP tool hash-locked version
MCP_NEO4J_CYPHER_VERSION = "mcp-neo4j-cypher==0.6.0"

PROJECT_ROOT = Path(__file__).parent.parent.parent
COMPOSE_FILE = PROJECT_ROOT / "infra" / "docker-compose.yaml"
MCP_DOCKERFILE = PROJECT_ROOT / "infra" / "mcp" / "Dockerfile"
MCP_REQUIREMENTS = PROJECT_ROOT / "infra" / "mcp" / "requirements.txt"


class TestRuntimeImagePins:
    """Verify that all Docker service images are pinned to full digest references."""

    def test_langflow_image_is_exactly_approved(self) -> None:
        """LangFlow must use exact approved digest, not mutable tag."""
        with open(COMPOSE_FILE) as f:
            compose = yaml.safe_load(f)

        assert compose["services"]["langflow"]["image"] == LANGFLOW_IMAGE, (
            f"LangFlow image must be {LANGFLOW_IMAGE}, got {compose['services']['langflow']['image']}"
        )

    def test_postgres_image_is_exactly_approved(self) -> None:
        """PostgreSQL must use exact approved digest, not mutable tag."""
        with open(COMPOSE_FILE) as f:
            compose = yaml.safe_load(f)

        assert compose["services"]["postgres"]["image"] == POSTGRES_IMAGE, (
            f"PostgreSQL image must be {POSTGRES_IMAGE}, got {compose['services']['postgres']['image']}"
        )

    def test_neo4j_image_is_exactly_approved(self) -> None:
        """Neo4j must use exact approved digest, not mutable tag."""
        with open(COMPOSE_FILE) as f:
            compose = yaml.safe_load(f)

        assert compose["services"]["neo4j"]["image"] == NEO4J_IMAGE, (
            f"Neo4j image must be {NEO4J_IMAGE}, got {compose['services']['neo4j']['image']}"
        )

    def test_mcp_base_image_is_exactly_approved(self) -> None:
        """MCP service's Python base image must use exact approved digest."""
        with open(MCP_DOCKERFILE) as f:
            dockerfile_content = f.read()

        # Extract FROM line
        from_match = re.search(r"^FROM\s+(\S+)", dockerfile_content, re.MULTILINE)
        assert from_match, "Dockerfile must have a FROM statement"

        actual_image = from_match.group(1)
        assert actual_image == PYTHON_BASE_IMAGE, (
            f"MCP base image must be {PYTHON_BASE_IMAGE}, got {actual_image}"
        )


class TestMcpDependencyPins:
    """Verify that MCP dependencies are hash-locked via pip-compile."""

    def test_requirements_file_exists(self) -> None:
        """requirements.txt must exist for hash-locked dependency pinning."""
        assert MCP_REQUIREMENTS.exists(), f"requirements.txt must exist at {MCP_REQUIREMENTS}"

    def test_requirements_file_uses_require_hashes_flag(self) -> None:
        """requirements.txt must be generated with --require-hashes flag."""
        with open(MCP_REQUIREMENTS) as f:
            content = f.read()

        # pip-compile with --generate-hashes produces hash-locked output
        # Check for either --generate-hashes or --require-hashes in the header comment
        assert "--generate-hashes" in content or "--require-hashes" in content, (
            "requirements.txt must contain hash-locking comment (generated by pip-compile --generate-hashes)"
        )

    def test_all_dependencies_have_hashes(self) -> None:
        """All package lines in requirements.txt must include sha256 hashes."""
        with open(MCP_REQUIREMENTS) as f:
            content = f.read()

        # Parse the requirements file as a whole (packages can span multiple lines)
        # Look for lines that declare packages (name==version) and verify they are followed by hash lines
        # Pattern: package==version (possibly with line continuation) followed by one or more --hash= lines

        # Split into logical blocks by looking for package declaration lines
        lines = content.split("\n")

        # Find all package declaration lines (contain ==)
        package_declarations = []
        for i, line in enumerate(lines):
            if "==" in line and not line.startswith("#"):
                # This is a package declaration, now find all its hashes
                j = i + 1
                hashes = []
                # Continue collecting lines until we hit a non-hash line
                while j < len(lines):
                    next_line = lines[j].strip()
                    if next_line.startswith("--hash="):
                        hashes.append(next_line)
                        j += 1
                    elif not next_line or next_line.startswith("#"):
                        j += 1
                    else:
                        break

                if hashes:
                    package_declarations.append((line.strip(), hashes))

        assert len(package_declarations) > 0, (
            "requirements.txt must contain pinned dependencies with hashes"
        )

        # Verify each declaration has at least one hash
        for pkg_line, hashes in package_declarations:
            assert len(hashes) > 0, f"Package line must be followed by hashes:\n{pkg_line}"
            # Verify each hash is valid sha256
            for hash_line in hashes:
                assert re.search(r"--hash=sha256:", hash_line), (
                    f"Hash line must be sha256:\n{hash_line}"
                )

    def test_mcp_neo4j_cypher_is_pinned(self) -> None:
        """mcp-neo4j-cypher must be pinned to approved version."""
        with open(MCP_REQUIREMENTS) as f:
            content = f.read()

        assert MCP_NEO4J_CYPHER_VERSION in content, (
            f"requirements.txt must pin mcp-neo4j-cypher to {MCP_NEO4J_CYPHER_VERSION}"
        )


class TestDockerfileHashLocking:
    """Verify that Dockerfile uses hash-locked requirements."""

    def test_dockerfile_uses_require_hashes_flag(self) -> None:
        """Dockerfile RUN pip install must use --require-hashes flag."""
        with open(MCP_DOCKERFILE) as f:
            dockerfile_content = f.read()

        # Look for pip install command with --require-hashes
        pip_install_pattern = r"pip\s+install.*--require-hashes"
        assert re.search(pip_install_pattern, dockerfile_content), (
            "Dockerfile must use 'pip install ... --require-hashes' to enforce hash verification"
        )

    def test_dockerfile_references_requirements_file(self) -> None:
        """Dockerfile must reference requirements.txt."""
        with open(MCP_DOCKERFILE) as f:
            dockerfile_content = f.read()

        assert "requirements.txt" in dockerfile_content, (
            "Dockerfile must reference requirements.txt (COPY and RUN pip install)"
        )
